apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kerron-Hutton/local-kubernetes-cluster
    targetRevision: main # repository branch name
    path: traefik
    helm:
      releaseName: argocd-helm-traefik
  destination:
    server: {{ .Values.destinationServerUrl }}
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true