apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kerron-Hutton/local-kubernetes-cluster
    path: argo-cd/child-applications
    targetRevision: main # repository branch name
    helm:
      releaseName: argocd-child-applications
      parameters:
        - name: destinationServerUrl
          value: https://kubernetes.default.svc
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true